### ISSUE TITLE
URL of CIFAR10 and CIFAR100.pt

### ISSUE THREAD

**Issue by zhuxunyu** [argenycw/ILA-DA#1]

**Comment by zhuxunyu** [comment]
In the readme.md, URL of CIFAR10 and CIFAR100.pt disappears. Please supplement as soon as possible.

**Comment by argenycw** [comment]
Please use this link at the moment: 
https://hkustconnect-my.sharepoint.com/:f:/g/personal/cwyan_connect_ust_hk/Emr-zwxiFIZHib5bLR2IVqcBXs_xD-R-cijh_ugMoMCazw?e=zGDU9c

I am sorry for the missing link. Will update readme.md as soon as possible.

**Comment by zhuxunyu** [comment]
Thank you!




---- Replied Message ----
| From | ***@***.***> |
| Date | 3/9/2023 11:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [argenycw/ILA-DA] URL of CIFAR10 and CIFAR100.pt (Issue #1) |

Please use this link at the moment:
https://hkustconnect-my.sharepoint.com/:f:/g/personal/cwyan_connect_ust_hk/Emr-zwxiFIZHib5bLR2IVqcBXs_xD-R-cijh_ugMoMCazw?e=zGDU9c

I am sorry for the missing link. Will update readme.md as soon as possible.
